; ============================================================
;  Power Debug System — Teensy 4.0 PlatformIO Konfiguration
; ============================================================
[env:teensy40]
platform  = teensy
board     = teensy40
framework = arduino

lib_deps =
    ; SPI-Slave-Bibliothek für Teensy 4.x (LPSPI Hardware)
    ; Repo: https://github.com/tonton81/SPISlave_T4
    https://github.com/tonton81/SPISlave_T4

monitor_speed   = 115200
upload_protocol = teensy-cli

build_flags =
    -DUSB_SERIAL          ; USB als serielle Schnittstelle
    -O2                   ; Optimierungsstufe 2
    -DACTIVE_CHANNELS=500 ; Anzahl aktiver Datenkanäle (anpassbar)
