// ============================================================
//  param_defaults.h — Auto-generated by Power Debug Monitor
//  Gespeichert am: 2026-07-12T22:50:13
//  NICHT MANUELL BEARBEITEN (wird von der GUI ueberschrieben)
// ============================================================
#pragma once

static const float PARAM_FLOAT_DEFAULTS[50] = {
    0.700000f, -2.700000f, 0.259247f, 7.463175f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.040000f, 0.120000f, 0.000000f, 0.000000f
};

static const bool PARAM_BOOL_DEFAULTS[50] = {
    false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
};

static const float PARAM_FAST_FLOAT_DEFAULTS[5] = {
    -29.583334f, 39.583332f, 99.776535f, 88.019867f, -16.076971f
};
