; ============================================================
;  Power Debug System — Teensy 4.0 PlatformIO Konfiguration
; ============================================================
[env:teensy40]
platform  = teensy
board     = teensy40
framework = arduino

monitor_speed   = 115200
upload_protocol = teensy-cli

build_flags =
    -DUSB_SERIAL          ; USB als serielle Schnittstelle
    -O2                   ; Optimierungsstufe 2
    -DACTIVE_CHANNELS=500 ; Anzahl aktiver Datenkanäle (anpassbar)
